create table public.participants (
  pid text primary key,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint participants_pid_format
    check (pid ~ '^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$')
);

create table public.vignette_responses (
  id bigint generated by default as identity primary key,
  pid text not null references public.participants(pid) on delete restrict,
  vignette_id text not null,
  vignette_number integer not null check (vignette_number between 1 and 24),
  task_type text not null,
  task_type_jitter_v text,
  iv2 text not null,
  iv2_jitter_v text,
  iv3 text not null,
  iv3_jitter_v text,
  iv4 text not null,
  iv4_jitter_v text,
  full_vignette_text text not null,
  q1_seek_input text not null,
  q2_incorporate text not null,
  q3 text not null,
  q4 text not null,
  q5 text not null,
  time_spent_ms integer not null check (time_spent_ms >= 0),
  started_at timestamptz not null,
  submitted_at timestamptz not null default now(),
  unique (pid, vignette_number),
  unique (pid, vignette_id)
);

alter table public.participants enable row level security;
alter table public.vignette_responses enable row level security;

-- Browser clients receive no table grants. The Next.js server uses the
-- service-role key, which bypasses RLS. Never expose that key to the browser.
revoke all on table public.participants from anon, authenticated;
revoke all on table public.vignette_responses from anon, authenticated;
grant select, insert, update on table public.participants to service_role;
grant select, insert, update on table public.vignette_responses to service_role;
grant usage, select on sequence public.vignette_responses_id_seq to service_role;

create view public.analysis_responses
with (security_invoker = true)
as
select
  r.pid as "PID",
  r.vignette_number as "Vignette #",
  r.task_type as "TaskType",
  r.task_type_jitter_v as "TaskType_JitterV",
  r.iv2 as "IV2",
  r.iv2_jitter_v as "IV2_JitterV",
  r.iv3 as "IV3",
  r.iv3_jitter_v as "IV3_JitterV",
  r.iv4 as "IV4",
  r.iv4_jitter_v as "IV4_JitterV",
  r.full_vignette_text as "FullVignetteText",
  r.q1_seek_input as "Q1_SeekInput",
  r.q2_incorporate as "Q2_Incorporate",
  r.q3 as "Q3_XXX",
  r.q4 as "Q4_XXX",
  r.q5 as "Q5_XXX",
  r.time_spent_ms as "TimeSpent"
from public.vignette_responses r
order by r.pid, r.vignette_number;

revoke all on table public.analysis_responses from anon, authenticated;
grant select on table public.analysis_responses to service_role;
